### ISSUE TITLE
Add setting to convert to mmol/l

### ISSUE THREAD

**Issue by danpowell88** [Rytiggy/api-watchface#4]
We need this for those who do use mg/dl

**Comment by Rytiggy** [comment]
I can add this to the companion app

**Comment by Rytiggy** [comment]
@danpowell88 I have added support for mmol and done some cleanup. grab the latest version of master. 
https://github.com/Rytiggy/api-watchface/commit/4c12d27319e1210b3ee32a4051754cca4521c79c

**Comment by PedanticAvenger** [comment]
The displayed numeric value is now correct but the graph y axis labels are still in mg/dl for me.
![api-watchface-fork-screenshot 1](https://user-images.githubusercontent.com/15637097/34963575-821af60a-fa06-11e7-8781-412cf2353a58.png)

**Comment by Rytiggy** [comment]
Yeah Im going to fix that when I make the scaling graph

**Comment by PedanticAvenger** [comment]
Great, otherwise this is looking great.  You uploaded just as I got it to work on my fork I was playing with.

**Comment by PedanticAvenger** [comment]
May simply be a thing that needs to be documented, I notice a .1 variance between xdrip and the watchface occasionally.  I suspect it is due to xdrip using "divide by 18" as the conversion math from mg/dl to mmol/L and the watchface using "multiply by 0.555".  Depending on how truncation math works there will be differences.

**Comment by danpowell88** [comment]
Yeah I've also seen this amongst various other sources, even between xdrip and nightscout as well as other watch faces
